[frontend]
3.93.72.13 ;COURSE="Ansible for NODE-1"
;172.31.23.186  ;COURSE="Ansible for NODE-2"

[catalouge]
172.31.27.249
[user]
172.31.27.248
[cart]
172.31.27.245

[roboshop:children]
frontend
catalouge
user
cart

[local]
localhost

; local group vars
; [local:vars]
; COURSE="Ansible"
; TRAINER="Sivakumar"
; DURATION="10HRS"

; [frontend:vars]
; COURSE="Ansible"
; TRAINER="Sivakumar"
; DURATION="10HRS"
